services:
  _defaults:
    public: false
    autowire: true

  Presta_Shop\Module\API_Resources\List\Module_Query_Builder:
    parent: 'prestashop.core.grid.abstract_query_builder'
    autowire: true

  prestashop.core.grid.data_factory.hook:
    class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
    public: true
    arguments:
      - '@prestashop.core.api.query_builder.hook'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'hook'

  prestashop.core.grid.data_factory.module:
    class: Presta_Shop\Module\API_Resources\List\Module_Grid_Data_Factory
    public: true
    arguments:
      - '@Presta_Shop\Module\API_Resources\List\Module_Query_Builder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'module'

  Presta_Shop\Module\API_Resources\Validation\Iframe_Validation_Groups_Resolver:
    arguments:
      - '@prestashop.adapter.legacy.configuration'

  Presta_Shop\Module\API_Resources\Command\Generate_Api_Tracking_Table_Command:
    tags:
      - { name: 'console.command' }

  # Custom normalizers for commands/queries that are very specific and cannot rely on generic solutions from the core
  Presta_Shop\Module\API_Resources\Api_Platform\Normalizer\Generate_Combinations_Serializer:
    autowire: true
    autoconfigure: true
    public: false

  Presta_Shop_Bundle\Api_Platform\Serializer\CQRS_Api_Serializer:
    class: Presta_Shop\Module\API_Resources\Serializer\Query_Parameter_Type_Cast_Serializer
    decorates: 'api_platform.serializer'
    autowire: true
    arguments:
      $decorated: '@.inner'
